apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
  namespace: ta-liberty-pipeline-pro
spec:
  inputs:
    resources:
      - name: git-repo
        type: git
      - name: image-registry
        type: image    
    params:
      - name: pathToDeploymentFiles
        description: Path to deployment yaml files
        default: /workspace/git-repo/operator/
      - name: namespace
        description: Namespace to deploy the application
        default: ta-liberty-apps    
      - name: imageName
        description: Image Name
        default: index.docker.io/gandhicloud/ta-wcare
      - name: imageTag
        description: Image Tag
        default: latest
  steps:
    - name: update-image-name-in-yaml
      image: ubuntu
      command: 
      - /bin/bash
      args:
        - -c
        - |
          echo "Started ......"
          
          VALUE0="$(inputs.resources.image-registry.url)"
          VALUE1="    repository: ${VALUE0%%:*}"
          VALUE2="    tag: ${VALUE0##*:}"
          PATH_TO_DEPLOYMENT_FILES="$(inputs.params.pathToDeploymentFiles)/application/application-cr.yaml"
          
          echo "Image name extraced : $VALUE1"
          echo "Image tag extraced : $VALUE2"
          echo "PATH_TO_DEPLOYMENT_FILES : $PATH_TO_DEPLOYMENT_FILES"

          echo "file before update......"
          cat "$PATH_TO_DEPLOYMENT_FILES"

          # sed -i "s#__IMAGE_NAME__#$VALUE1#g" $PATH_TO_DEPLOYMENT_FILES
          # sed -i "s#__IMAGE_TAG__#$VALUE2#g" $PATH_TO_DEPLOYMENT_FILES

          sed -i "s#.*repository:.*#$VALUE1#g" $PATH_TO_DEPLOYMENT_FILES
          sed -i "s#.*tag:.*#$VALUE2#g" $PATH_TO_DEPLOYMENT_FILES
          
          echo "file after update......"
          cat "$PATH_TO_DEPLOYMENT_FILES"

          echo "Completed ......" 
    # - name: update-image-name-in-yaml
    #   image: alpine
    #   command: ["sed"]
    #   args:
    #     - "-i"
    #     - "-e"
    #     - "s;__IMAGE_NAME__;$(inputs.params.imageName);g"
    #     - "$(inputs.params.pathToDeploymentFiles)/application/application-cr.yaml"
    # - name: update-image-tag-in-yaml
    #   image: alpine
    #   command: ["sed"]
    #   args:
    #     - "-i"
    #     - "-e"
    #     - "s;__IMAGE_TAG__;$(inputs.params.imageTag);g"
    #     - "$(inputs.params.pathToDeploymentFiles)/application/application-cr.yaml"     
    # - name: kubectl-create-namespace
    #   image: lachlanevenson/k8s-kubectl
    #   command: ["kubectl"]
    #   args:
    #     - "create"
    #     - "namespace"
    #     - "$(inputs.params.namespace)"
    # - name: kubectl-set-context-namespace
    #   image: lachlanevenson/k8s-kubectl
    #   command: ["kubectl"]
    #   args:
    #     - "config"
    #     - "set-context"
    #     - "--current"
    #     - "--namespace=$(inputs.params.namespace)"        
    - name: kubectl-apply-deployment-files
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.params.pathToDeploymentFiles)"
        - "-R"
        - "--validate=false"